[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.sdist]
include = ["mediacloud/py.typed"]

[project]
name = "mediacloud"
version = "6.0.0"
authors = [
    {name = "Rahul Bhargava", email = "r.bhargava@northeastern.edu"},
]
description = "Media Cloud API Client Library"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "requests == 2.*",
    "requests-ratelimiter >= 0.10",
]

[project.optional-dependencies]
dev = [
    "pre-commit", "flake8", "mypy", "isort", "types-urllib3", "types-requests", "python-dotenv"
]
test = [
    "pytest"
]

[project.urls]
"Homepage" = "https://mediacloud.org"
"Repository" = "https://github.com/mediacloud/api-client"
"Bug Tracker" = "https://github.com/mediacloud/api-client/issues"

[tool.mypy]
# from story-indexer,
# from https://blog.wolt.com/engineering/2021/09/30/professional-grade-mypy-configuration/
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
show_error_codes = true
